package crap

import (
	"go/token"
	"math"
	"os"
	"path/filepath"
	"testing"

	"github.com/fzipp/gocyclo"
)

// makeStat constructs a gocyclo.Stat for testing.
func makeStat(pkg, fn, file string, line, complexity int) gocyclo.Stat {
	return gocyclo.Stat{
		PkgName:    pkg,
		FuncName:   fn,
		Complexity: complexity,
		Pos:        token.Position{Filename: file, Line: line},
	}
}

// makeCoverMap constructs a coverMaps for testing from file:line -> pct pairs.
func makeCoverMap(entries map[coverKey]float64) coverMaps {
	base := make(map[coverKey]float64, len(entries))
	for k, v := range entries {
		base[coverKey{file: filepath.Base(k.file), line: k.line}] = v
	}
	return coverMaps{exact: entries, basename: base}
}

func TestComputeScores_BasicCRAP(t *testing.T) {
	stats := []gocyclo.Stat{
		makeStat("pkg", "Foo", "/src/foo.go", 10, 5),
	}
	cm := makeCoverMap(map[coverKey]float64{
		{file: "/src/foo.go", line: 10}: 80.0,
	})
	opts := DefaultOptions()

	scores := computeScores(stats, cm, opts)

	if len(scores) != 1 {
		t.Fatalf("expected 1 score, got %d", len(scores))
	}
	s := scores[0]
	if s.Package != "pkg" {
		t.Errorf("expected Package 'pkg', got %q", s.Package)
	}
	if s.Function != "Foo" {
		t.Errorf("expected Function 'Foo', got %q", s.Function)
	}
	if s.Complexity != 5 {
		t.Errorf("expected Complexity 5, got %d", s.Complexity)
	}
	if s.LineCoverage != 80.0 {
		t.Errorf("expected LineCoverage 80.0, got %f", s.LineCoverage)
	}
	expectedCRAP := Formula(5, 80.0)
	if math.Abs(s.CRAP-expectedCRAP) > 0.001 {
		t.Errorf("expected CRAP %f, got %f", expectedCRAP, s.CRAP)
	}
}

func TestComputeScores_SkipsTestFiles(t *testing.T) {
	stats := []gocyclo.Stat{
		makeStat("pkg", "Foo", "/src/foo.go", 10, 5),
		makeStat("pkg", "TestBar", "/src/foo_test.go", 20, 3),
	}
	cm := makeCoverMap(map[coverKey]float64{
		{file: "/src/foo.go", line: 10}: 80.0,
	})
	opts := DefaultOptions()

	scores := computeScores(stats, cm, opts)

	if len(scores) != 1 {
		t.Fatalf("expected 1 score (test file skipped), got %d", len(scores))
	}
	if scores[0].Function != "Foo" {
		t.Errorf("expected Function 'Foo', got %q", scores[0].Function)
	}
}

func TestComputeScores_SkipsGeneratedFiles(t *testing.T) {
	// Create a temporary generated file.
	tmpDir := t.TempDir()
	genFile := filepath.Join(tmpDir, "generated.go")
	err := os.WriteFile(genFile, []byte("// Code generated by test; DO NOT EDIT.\npackage foo\nfunc Gen() {}\n"), 0644)
	if err != nil {
		t.Fatalf("creating temp file: %v", err)
	}
	normalFile := filepath.Join(tmpDir, "normal.go")
	err = os.WriteFile(normalFile, []byte("package foo\nfunc Normal() {}\n"), 0644)
	if err != nil {
		t.Fatalf("creating temp file: %v", err)
	}

	stats := []gocyclo.Stat{
		makeStat("foo", "Gen", genFile, 3, 2),
		makeStat("foo", "Normal", normalFile, 2, 3),
	}
	cm := makeCoverMap(map[coverKey]float64{})

	// IgnoreGenerated = true (default): generated file skipped.
	opts := DefaultOptions()
	scores := computeScores(stats, cm, opts)
	if len(scores) != 1 {
		t.Fatalf("expected 1 score (generated skipped), got %d", len(scores))
	}
	if scores[0].Function != "Normal" {
		t.Errorf("expected Function 'Normal', got %q", scores[0].Function)
	}

	// IgnoreGenerated = false: generated file included.
	opts.IgnoreGenerated = false
	scores = computeScores(stats, cm, opts)
	if len(scores) != 2 {
		t.Fatalf("expected 2 scores (generated included), got %d", len(scores))
	}
}

func TestComputeScores_ZeroCoverage(t *testing.T) {
	stats := []gocyclo.Stat{
		makeStat("pkg", "Uncovered", "/src/foo.go", 10, 4),
	}
	// Empty coverage map — function has no coverage data.
	cm := makeCoverMap(map[coverKey]float64{})
	opts := DefaultOptions()

	scores := computeScores(stats, cm, opts)

	if len(scores) != 1 {
		t.Fatalf("expected 1 score, got %d", len(scores))
	}
	if scores[0].LineCoverage != 0.0 {
		t.Errorf("expected LineCoverage 0.0 for uncovered function, got %f", scores[0].LineCoverage)
	}
	// With 0% coverage and complexity 4: CRAP = 4^2 + 4 = 20
	expectedCRAP := Formula(4, 0.0)
	if math.Abs(scores[0].CRAP-expectedCRAP) > 0.001 {
		t.Errorf("expected CRAP %f, got %f", expectedCRAP, scores[0].CRAP)
	}
}

func TestComputeScores_GazeCRAP(t *testing.T) {
	stats := []gocyclo.Stat{
		makeStat("pkg", "Foo", "/src/foo.go", 10, 10),
	}
	cm := makeCoverMap(map[coverKey]float64{
		{file: "/src/foo.go", line: 10}: 90.0,
	})
	opts := DefaultOptions()
	opts.ContractCoverageFunc = func(pkg, fn string) (float64, bool) {
		if pkg == "pkg" && fn == "Foo" {
			return 75.0, true
		}
		return 0, false
	}

	scores := computeScores(stats, cm, opts)

	if len(scores) != 1 {
		t.Fatalf("expected 1 score, got %d", len(scores))
	}
	s := scores[0]
	if s.ContractCoverage == nil {
		t.Fatal("expected non-nil ContractCoverage")
	}
	if *s.ContractCoverage != 75.0 {
		t.Errorf("expected ContractCoverage 75.0, got %f", *s.ContractCoverage)
	}
	if s.GazeCRAP == nil {
		t.Fatal("expected non-nil GazeCRAP")
	}
	expectedGazeCRAP := Formula(10, 75.0)
	if math.Abs(*s.GazeCRAP-expectedGazeCRAP) > 0.001 {
		t.Errorf("expected GazeCRAP %f, got %f", expectedGazeCRAP, *s.GazeCRAP)
	}
	if s.Quadrant == nil {
		t.Fatal("expected non-nil Quadrant")
	}
}

func TestComputeScores_NoGazeCRAP(t *testing.T) {
	stats := []gocyclo.Stat{
		makeStat("pkg", "Foo", "/src/foo.go", 10, 5),
	}
	cm := makeCoverMap(map[coverKey]float64{
		{file: "/src/foo.go", line: 10}: 80.0,
	})
	opts := DefaultOptions()
	// ContractCoverageFunc is nil (default).

	scores := computeScores(stats, cm, opts)

	if len(scores) != 1 {
		t.Fatalf("expected 1 score, got %d", len(scores))
	}
	s := scores[0]
	if s.ContractCoverage != nil {
		t.Errorf("expected nil ContractCoverage, got %v", *s.ContractCoverage)
	}
	if s.GazeCRAP != nil {
		t.Errorf("expected nil GazeCRAP, got %v", *s.GazeCRAP)
	}
	if s.Quadrant != nil {
		t.Errorf("expected nil Quadrant, got %v", *s.Quadrant)
	}
}

func TestComputeScores_GazeCRAPNotFound(t *testing.T) {
	stats := []gocyclo.Stat{
		makeStat("pkg", "Foo", "/src/foo.go", 10, 5),
	}
	cm := makeCoverMap(map[coverKey]float64{
		{file: "/src/foo.go", line: 10}: 80.0,
	})
	opts := DefaultOptions()
	// ContractCoverageFunc is set but returns false for this function.
	opts.ContractCoverageFunc = func(pkg, fn string) (float64, bool) {
		return 0, false
	}

	scores := computeScores(stats, cm, opts)

	if len(scores) != 1 {
		t.Fatalf("expected 1 score, got %d", len(scores))
	}
	s := scores[0]
	if s.ContractCoverage != nil {
		t.Errorf("expected nil ContractCoverage when callback returns false, got %v", *s.ContractCoverage)
	}
	if s.GazeCRAP != nil {
		t.Errorf("expected nil GazeCRAP when callback returns false, got %v", *s.GazeCRAP)
	}
	if s.Quadrant != nil {
		t.Errorf("expected nil Quadrant when callback returns false, got %v", *s.Quadrant)
	}
}
