package crap

import (
	"go/token"
	"math"
	"os"
	"path/filepath"
	"testing"

	"github.com/fzipp/gocyclo"
)

// makeStat constructs a gocyclo.Stat for testing.
func makeStat(pkg, fn, file string, line, complexity int) gocyclo.Stat {
	return gocyclo.Stat{
		PkgName:    pkg,
		FuncName:   fn,
		Complexity: complexity,
		Pos:        token.Position{Filename: file, Line: line},
	}
}

// makeCoverMap constructs a coverMaps for testing from file:line -> pct pairs.
func makeCoverMap(entries map[coverKey]float64) coverMaps {
	base := make(map[coverKey]float64, len(entries))
	for k, v := range entries {
		base[coverKey{file: filepath.Base(k.file), line: k.line}] = v
	}
	return coverMaps{exact: entries, basename: base}
}

func TestComputeScores_BasicCRAP(t *testing.T) {
	stats := []gocyclo.Stat{
		makeStat("pkg", "Foo", "/src/foo.go", 10, 5),
	}
	cm := makeCoverMap(map[coverKey]float64{
		{file: "/src/foo.go", line: 10}: 80.0,
	})
	opts := DefaultOptions()

	scores := computeScores(stats, cm, opts)

	if len(scores) != 1 {
		t.Fatalf("expected 1 score, got %d", len(scores))
	}
	s := scores[0]
	if s.Package != "pkg" {
		t.Errorf("expected Package 'pkg', got %q", s.Package)
	}
	if s.Function != "Foo" {
		t.Errorf("expected Function 'Foo', got %q", s.Function)
	}
	if s.Complexity != 5 {
		t.Errorf("expected Complexity 5, got %d", s.Complexity)
	}
	if s.LineCoverage != 80.0 {
		t.Errorf("expected LineCoverage 80.0, got %f", s.LineCoverage)
	}
	expectedCRAP := Formula(5, 80.0)
	if math.Abs(s.CRAP-expectedCRAP) > 0.001 {
		t.Errorf("expected CRAP %f, got %f", expectedCRAP, s.CRAP)
	}
}

func TestComputeScores_SkipsTestFiles(t *testing.T) {
	stats := []gocyclo.Stat{
		makeStat("pkg", "Foo", "/src/foo.go", 10, 5),
		makeStat("pkg", "TestBar", "/src/foo_test.go", 20, 3),
	}
	cm := makeCoverMap(map[coverKey]float64{
		{file: "/src/foo.go", line: 10}: 80.0,
	})
	opts := DefaultOptions()

	scores := computeScores(stats, cm, opts)

	if len(scores) != 1 {
		t.Fatalf("expected 1 score (test file skipped), got %d", len(scores))
	}
	if scores[0].Function != "Foo" {
		t.Errorf("expected Function 'Foo', got %q", scores[0].Function)
	}
}

func TestComputeScores_SkipsGeneratedFiles(t *testing.T) {
	// Create a temporary generated file.
	tmpDir := t.TempDir()
	genFile := filepath.Join(tmpDir, "generated.go")
	err := os.WriteFile(genFile, []byte("// Code generated by test; DO NOT EDIT.\npackage foo\nfunc Gen() {}\n"), 0644)
	if err != nil {
		t.Fatalf("creating temp file: %v", err)
	}
	normalFile := filepath.Join(tmpDir, "normal.go")
	err = os.WriteFile(normalFile, []byte("package foo\nfunc Normal() {}\n"), 0644)
	if err != nil {
		t.Fatalf("creating temp file: %v", err)
	}

	stats := []gocyclo.Stat{
		makeStat("foo", "Gen", genFile, 3, 2),
		makeStat("foo", "Normal", normalFile, 2, 3),
	}
	cm := makeCoverMap(map[coverKey]float64{})

	// IgnoreGenerated = true (default): generated file skipped.
	opts := DefaultOptions()
	scores := computeScores(stats, cm, opts)
	if len(scores) != 1 {
		t.Fatalf("expected 1 score (generated skipped), got %d", len(scores))
	}
	if scores[0].Function != "Normal" {
		t.Errorf("expected Function 'Normal', got %q", scores[0].Function)
	}

	// IgnoreGenerated = false: generated file included.
	opts.IgnoreGenerated = false
	scores = computeScores(stats, cm, opts)
	if len(scores) != 2 {
		t.Fatalf("expected 2 scores (generated included), got %d", len(scores))
	}
}

func TestComputeScores_ZeroCoverage(t *testing.T) {
	stats := []gocyclo.Stat{
		makeStat("pkg", "Uncovered", "/src/foo.go", 10, 4),
	}
	// Empty coverage map — function has no coverage data.
	cm := makeCoverMap(map[coverKey]float64{})
	opts := DefaultOptions()

	scores := computeScores(stats, cm, opts)

	if len(scores) != 1 {
		t.Fatalf("expected 1 score, got %d", len(scores))
	}
	if scores[0].LineCoverage != 0.0 {
		t.Errorf("expected LineCoverage 0.0 for uncovered function, got %f", scores[0].LineCoverage)
	}
	// With 0% coverage and complexity 4: CRAP = 4^2 + 4 = 20
	expectedCRAP := Formula(4, 0.0)
	if math.Abs(scores[0].CRAP-expectedCRAP) > 0.001 {
		t.Errorf("expected CRAP %f, got %f", expectedCRAP, scores[0].CRAP)
	}
}

func TestComputeScores_GazeCRAP(t *testing.T) {
	stats := []gocyclo.Stat{
		makeStat("pkg", "Foo", "/src/foo.go", 10, 10),
	}
	cm := makeCoverMap(map[coverKey]float64{
		{file: "/src/foo.go", line: 10}: 90.0,
	})
	opts := DefaultOptions()
	opts.ContractCoverageFunc = func(pkg, fn string) (ContractCoverageInfo, bool) {
		if pkg == "pkg" && fn == "Foo" {
			return ContractCoverageInfo{Percentage: 75.0}, true
		}
		return ContractCoverageInfo{}, false
	}

	scores := computeScores(stats, cm, opts)

	if len(scores) != 1 {
		t.Fatalf("expected 1 score, got %d", len(scores))
	}
	s := scores[0]
	if s.ContractCoverage == nil {
		t.Fatal("expected non-nil ContractCoverage")
	}
	if *s.ContractCoverage != 75.0 {
		t.Errorf("expected ContractCoverage 75.0, got %f", *s.ContractCoverage)
	}
	if s.GazeCRAP == nil {
		t.Fatal("expected non-nil GazeCRAP")
	}
	expectedGazeCRAP := Formula(10, 75.0)
	if math.Abs(*s.GazeCRAP-expectedGazeCRAP) > 0.001 {
		t.Errorf("expected GazeCRAP %f, got %f", expectedGazeCRAP, *s.GazeCRAP)
	}
	if s.Quadrant == nil {
		t.Fatal("expected non-nil Quadrant")
	}
}

func TestComputeScores_NoGazeCRAP(t *testing.T) {
	stats := []gocyclo.Stat{
		makeStat("pkg", "Foo", "/src/foo.go", 10, 5),
	}
	cm := makeCoverMap(map[coverKey]float64{
		{file: "/src/foo.go", line: 10}: 80.0,
	})
	opts := DefaultOptions()
	// ContractCoverageFunc is nil (default).

	scores := computeScores(stats, cm, opts)

	if len(scores) != 1 {
		t.Fatalf("expected 1 score, got %d", len(scores))
	}
	s := scores[0]
	if s.ContractCoverage != nil {
		t.Errorf("expected nil ContractCoverage, got %v", *s.ContractCoverage)
	}
	if s.GazeCRAP != nil {
		t.Errorf("expected nil GazeCRAP, got %v", *s.GazeCRAP)
	}
	if s.Quadrant != nil {
		t.Errorf("expected nil Quadrant, got %v", *s.Quadrant)
	}
}

func TestComputeScores_GazeCRAPNotFound(t *testing.T) {
	stats := []gocyclo.Stat{
		makeStat("pkg", "Foo", "/src/foo.go", 10, 5),
	}
	cm := makeCoverMap(map[coverKey]float64{
		{file: "/src/foo.go", line: 10}: 80.0,
	})
	opts := DefaultOptions()
	// ContractCoverageFunc is set but returns false for this function.
	opts.ContractCoverageFunc = func(pkg, fn string) (ContractCoverageInfo, bool) {
		return ContractCoverageInfo{}, false
	}

	scores := computeScores(stats, cm, opts)

	if len(scores) != 1 {
		t.Fatalf("expected 1 score, got %d", len(scores))
	}
	s := scores[0]
	if s.ContractCoverage != nil {
		t.Errorf("expected nil ContractCoverage when callback returns false, got %v", *s.ContractCoverage)
	}
	if s.GazeCRAP != nil {
		t.Errorf("expected nil GazeCRAP when callback returns false, got %v", *s.GazeCRAP)
	}
	if s.Quadrant != nil {
		t.Errorf("expected nil Quadrant when callback returns false, got %v", *s.Quadrant)
	}
}

// --- FixStrategy Tests ---

func TestAssignFixStrategy_Decompose(t *testing.T) {
	// Complexity 20 >= threshold 15, coverage 80% > 0.
	s := Score{Complexity: 20, LineCoverage: 80, CRAP: Formula(20, 80)}
	got := assignFixStrategy(s, 15)
	if got == nil {
		t.Fatal("expected non-nil FixStrategy")
	}
	if *got != FixDecompose {
		t.Errorf("expected FixDecompose, got %q", *got)
	}
}

func TestAssignFixStrategy_DecomposeAndTest(t *testing.T) {
	// Complexity 18 >= threshold 15, coverage 0%.
	s := Score{Complexity: 18, LineCoverage: 0, CRAP: Formula(18, 0)}
	got := assignFixStrategy(s, 15)
	if got == nil {
		t.Fatal("expected non-nil FixStrategy")
	}
	if *got != FixDecomposeAndTest {
		t.Errorf("expected FixDecomposeAndTest, got %q", *got)
	}
}

func TestAssignFixStrategy_AddTests(t *testing.T) {
	// Complexity 8 < threshold 15, coverage 0%.
	s := Score{Complexity: 8, LineCoverage: 0, CRAP: Formula(8, 0)}
	got := assignFixStrategy(s, 15)
	if got == nil {
		t.Fatal("expected non-nil FixStrategy")
	}
	if *got != FixAddTests {
		t.Errorf("expected FixAddTests, got %q", *got)
	}
}

func TestAssignFixStrategy_AddAssertions(t *testing.T) {
	// Complexity 6, line coverage 0% (gives CRAP 42, above threshold),
	// but quadrant Q3 means tests exist with inadequate assertions.
	// In practice Q3 functions have high line coverage but low contract
	// coverage — the CRAP score is high because GazeCRAP uses contract
	// coverage (which is low) rather than line coverage.
	q := Q3SimpleButUnderspecified
	s := Score{
		Complexity:   6,
		LineCoverage: 0,
		CRAP:         Formula(6, 0), // CRAP 42, above threshold
		Quadrant:     &q,
	}
	got := assignFixStrategy(s, 15)
	if got == nil {
		t.Fatal("expected non-nil FixStrategy")
	}
	if *got != FixAddAssertions {
		t.Errorf("expected FixAddAssertions, got %q", *got)
	}
}

func TestAssignFixStrategy_BelowThreshold(t *testing.T) {
	// CRAP 8.0 < threshold 15, should return nil.
	s := Score{Complexity: 3, LineCoverage: 80, CRAP: Formula(3, 80)}
	got := assignFixStrategy(s, 15)
	if got != nil {
		t.Errorf("expected nil FixStrategy for below-threshold function, got %q", *got)
	}
}

func TestComputeScores_FixStrategyAssigned(t *testing.T) {
	// Verify computeScores assigns FixStrategy to above-threshold scores.
	stats := []gocyclo.Stat{
		makeStat("pkg", "HighComplexity", "/src/foo.go", 10, 20),
		makeStat("pkg", "LowCRAP", "/src/foo.go", 20, 2),
	}
	cm := makeCoverMap(map[coverKey]float64{
		{file: "/src/foo.go", line: 10}: 50.0,
		{file: "/src/foo.go", line: 20}: 90.0,
	})
	opts := DefaultOptions()

	scores := computeScores(stats, cm, opts)
	if len(scores) != 2 {
		t.Fatalf("expected 2 scores, got %d", len(scores))
	}

	// HighComplexity (cx=20, cov=50%) should get FixDecompose.
	if scores[0].FixStrategy == nil {
		t.Fatal("expected non-nil FixStrategy for HighComplexity")
	}
	if *scores[0].FixStrategy != FixDecompose {
		t.Errorf("expected FixDecompose for HighComplexity, got %q", *scores[0].FixStrategy)
	}

	// LowCRAP (cx=2, cov=90%) should have nil FixStrategy.
	if scores[1].FixStrategy != nil {
		t.Errorf("expected nil FixStrategy for LowCRAP, got %q", *scores[1].FixStrategy)
	}
}

func TestBuildSummary_FixStrategyCounts(t *testing.T) {
	decomposeFS := FixDecompose
	addTestsFS := FixAddTests
	scores := []Score{
		{Complexity: 20, LineCoverage: 80, CRAP: 20, FixStrategy: &decomposeFS},
		{Complexity: 18, LineCoverage: 50, CRAP: 18, FixStrategy: &decomposeFS},
		{Complexity: 8, LineCoverage: 0, CRAP: 72, FixStrategy: &addTestsFS},
		{Complexity: 3, LineCoverage: 90, CRAP: 3.1}, // below threshold, no strategy
	}
	opts := DefaultOptions()
	summary := buildSummary(scores, opts)

	if summary.FixStrategyCounts == nil {
		t.Fatal("expected non-nil FixStrategyCounts")
	}
	if summary.FixStrategyCounts[FixDecompose] != 2 {
		t.Errorf("expected decompose=2, got %d", summary.FixStrategyCounts[FixDecompose])
	}
	if summary.FixStrategyCounts[FixAddTests] != 1 {
		t.Errorf("expected add_tests=1, got %d", summary.FixStrategyCounts[FixAddTests])
	}
	if summary.FixStrategyCounts[FixAddAssertions] != 0 {
		t.Errorf("expected add_assertions=0, got %d", summary.FixStrategyCounts[FixAddAssertions])
	}
}

func TestComputeScores_CoverageReason_AllAmbiguous(t *testing.T) {
	stats := []gocyclo.Stat{
		makeStat("pkg", "Foo", "/src/foo.go", 10, 5),
	}
	cm := makeCoverMap(map[coverKey]float64{
		{file: "/src/foo.go", line: 10}: 80.0,
	})
	opts := DefaultOptions()
	opts.ContractCoverageFunc = func(pkg, fn string) (ContractCoverageInfo, bool) {
		return ContractCoverageInfo{
			Percentage:    0,
			Reason:        "all_effects_ambiguous",
			MinConfidence: 78,
			MaxConfidence: 79,
		}, true
	}

	scores := computeScores(stats, cm, opts)
	if len(scores) != 1 {
		t.Fatalf("expected 1 score, got %d", len(scores))
	}
	s := scores[0]
	if s.ContractCoverageReason == nil {
		t.Fatal("expected non-nil ContractCoverageReason")
	}
	if *s.ContractCoverageReason != "all_effects_ambiguous" {
		t.Errorf("expected 'all_effects_ambiguous', got %q", *s.ContractCoverageReason)
	}
	if s.EffectConfidenceRange == nil {
		t.Fatal("expected non-nil EffectConfidenceRange")
	}
	if s.EffectConfidenceRange[0] != 78 || s.EffectConfidenceRange[1] != 79 {
		t.Errorf("expected confidence range [78,79], got [%d,%d]",
			s.EffectConfidenceRange[0], s.EffectConfidenceRange[1])
	}
}

func TestComputeScores_CoverageReason_Normal(t *testing.T) {
	stats := []gocyclo.Stat{
		makeStat("pkg", "Foo", "/src/foo.go", 10, 5),
	}
	cm := makeCoverMap(map[coverKey]float64{
		{file: "/src/foo.go", line: 10}: 80.0,
	})
	opts := DefaultOptions()
	opts.ContractCoverageFunc = func(pkg, fn string) (ContractCoverageInfo, bool) {
		return ContractCoverageInfo{Percentage: 85.0}, true
	}

	scores := computeScores(stats, cm, opts)
	if len(scores) != 1 {
		t.Fatalf("expected 1 score, got %d", len(scores))
	}
	if scores[0].ContractCoverageReason != nil {
		t.Errorf("expected nil ContractCoverageReason for normal coverage, got %q",
			*scores[0].ContractCoverageReason)
	}
	if scores[0].EffectConfidenceRange != nil {
		t.Errorf("expected nil EffectConfidenceRange for normal coverage")
	}
}

func TestBuildSummary_RecommendedActions(t *testing.T) {
	addTests := FixAddTests
	addAssertions := FixAddAssertions
	decomposeAndTest := FixDecomposeAndTest
	decompose := FixDecompose

	scores := []Score{
		{Function: "LowCRAP", Complexity: 3, CRAP: 3.1},                                       // below threshold, no strategy
		{Function: "DecomposeHigh", Complexity: 20, CRAP: 100, FixStrategy: &decompose},       // decompose, CRAP 100
		{Function: "AddTestsLow", Complexity: 5, CRAP: 25, FixStrategy: &addTests},            // add_tests, CRAP 25
		{Function: "AddTestsHigh", Complexity: 8, CRAP: 72, FixStrategy: &addTests},           // add_tests, CRAP 72
		{Function: "AddAssertions", Complexity: 6, CRAP: 36, FixStrategy: &addAssertions},     // add_assertions, CRAP 36
		{Function: "DecompAndTest", Complexity: 15, CRAP: 50, FixStrategy: &decomposeAndTest}, // decompose_and_test, CRAP 50
	}

	opts := DefaultOptions()
	summary := buildSummary(scores, opts)

	// (a) Only CRAPload functions (those with FixStrategy) appear.
	if len(summary.RecommendedActions) != 5 {
		t.Fatalf("expected 5 recommended actions, got %d", len(summary.RecommendedActions))
	}

	// (b) Sorted by strategy priority: add_tests(0), add_assertions(1), decompose_and_test(2), decompose(3).
	// Within add_tests: CRAP 72 before CRAP 25.
	expected := []struct {
		function string
		strategy FixStrategy
	}{
		{"AddTestsHigh", FixAddTests},
		{"AddTestsLow", FixAddTests},
		{"AddAssertions", FixAddAssertions},
		{"DecompAndTest", FixDecomposeAndTest},
		{"DecomposeHigh", FixDecompose},
	}

	for i, e := range expected {
		if summary.RecommendedActions[i].Function != e.function {
			t.Errorf("action[%d].Function = %q, want %q", i, summary.RecommendedActions[i].Function, e.function)
		}
		if summary.RecommendedActions[i].FixStrategy != e.strategy {
			t.Errorf("action[%d].FixStrategy = %q, want %q", i, summary.RecommendedActions[i].FixStrategy, e.strategy)
		}
	}
}

func TestBuildSummary_RecommendedActions_Truncated(t *testing.T) {
	addTests := FixAddTests
	// Create 25 CRAPload functions.
	var scores []Score
	for i := 0; i < 25; i++ {
		scores = append(scores, Score{
			Function:    "Func" + string(rune('A'+i)),
			Complexity:  10,
			CRAP:        float64(30 + i),
			FixStrategy: &addTests,
		})
	}

	opts := DefaultOptions()
	summary := buildSummary(scores, opts)

	// (c) Truncated to 20.
	if len(summary.RecommendedActions) != 20 {
		t.Errorf("expected 20 recommended actions (truncated), got %d", len(summary.RecommendedActions))
	}
}
